SHELL := /bin/bash

# read the config generated by the workflow; fall back to local defaults if .env is absent
-include .env

DOCKER_IMAGE_NAME ?= my-app   # default image name for local runs without .env
TAG ?= local                    # default tag for local runs without .env

export DOCKER_IMAGE_NAME   # exported so docker compose can substitute ${...} in compose.yml
export TAG

.DEFAULT_GOAL := help   # running bare `make` shows help

.PHONY: help lint build run test push down   # these are not real files, avoid name clashes

help:
	@echo "make lint  - Check Dockerfile"
	@echo "make build - Build Docker image"
	@echo "make run   - Start container and wait for health check"
	@echo "make test  - Test HTTP endpoint"
	@echo "make push  - Push image to registry"
	@echo "make down  - Remove demo container"

lint:
	docker run --rm -i hadolint/hadolint:v2.12.0 < Dockerfile || true   # static lint; || true keeps CI going on warnings

build:
	docker build -t "$(DOCKER_IMAGE_NAME):$(TAG)" .   # build using name/tag from .env (or defaults)

run:
	docker compose up -d --wait --wait-timeout 60   # start in background, wait for healthcheck (max 60s)

test:
	curl --fail --show-error http://127.0.0.1:5000/   # non-2xx makes curl exit non-zero, failing this step

push:
	docker push "$(DOCKER_IMAGE_NAME):$(TAG)"   # push to the registry named in .env (usually ECR)

down:
	docker compose down --remove-orphans   # tear down; --remove-orphans also drops removed services
